version: "3"

services:
  wetty:
    build: .
    image: redbrick/wetty
    container_name: wetty
    tty: true
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      SSHHOST: 'localhost'
      SSHPORT: 22
