version: "3"
services:
  wetty:
    image: butlerx/wetty
    container_name: wetty
    tty: true
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      SSHHOST: 'localhost'
      SSHPORT: 22
